config/routes.rb
Taki::Application.routes.draw do
  
  
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root 'project_files#top'
  resources :project_files do
    member do
      get 'z_index'
      get 'similarity'
    end
  end

  

end

app/models/project_file.rb
class ProjectFile < ActiveRecord::Base
  attr_accessible :attachment, :status
  has_many :project_file_media_queries
  has_many :project_file_selectors

  after_commit :css_parser, :on => [:create, :update]

  has_attached_file :attachment

  validates_attachment :attachment, presence: true,
    content_type: { content_type: ["text/css"] },
    size: { less_than: 10.megabytes }

  def attachment_contents
    attachment.copy_to_local_file.read
  end

  def css_parser
    parse = CssParser::Parser.new
    parse.class_eval { attr_reader :rules }

    parse.load_uri!(self.attachment.path)
    parse.rules.each do |rule|
      project_file_selector = self.project_file_selectors.create({
        :name => rule[:rules].selectors.join(', '),
        :raw => rule[:rules].to_s,
      })

      project_file_media_query = self.project_file_media_queries.create({
        :name => rule[:media_types].join(' '),
        :project_file_selector_id => project_file_selector.id,
      }) unless rule[:media_types].blank?

      rule[:rules].class_eval { attr_reader :declarations }
      rule[:rules].declarations.keys.each_with_index do |name, i|
        project_file_selector.project_file_selector_properties.create({
          :name => name,
          :value => rule[:rules].declarations.values[i][:value],
          :is_important => rule[:rules].declarations.values[i][:is_important]
        })
      end
    end
  end

  def calc_similarities()

    similarities = []
    combinations = []

    selector_ids = self.project_file_selectors.where(project_file_id: self.id).pluck(:id)

    selector_ids.each_with_index do |id_a, index|
      for id_b in selector_ids[index+1..-1] do
        combinations << %W|#{id_a} #{id_b}|
      end
    end

    # @todo parallelization
    for selector_ids in combinations do
      match_prop = 0
      match_val = 0
      properties_a = ProjectFileSelectorProperty.where(project_file_selector_id: selector_ids[0]).map(&:serializable_hash)
      properties_b = ProjectFileSelectorProperty.where(project_file_selector_id: selector_ids[1]).map(&:serializable_hash)

      properties_a.each_with_index do |property_a, index_a|
        properties_b.each_with_index do |property_b, index_b|
          if property_a['name'] == property_b['name'] then
            match_prop+=1
            if property_a['value'] == property_b['value'] then
              match_val+=1
            end
          end
        end
      end

      unique_property_count = properties_a.count + properties_b.count - match_prop

      similarities << ProjectFileSelectorSimilarity.create(
        :current_selector_id => selector_ids[0],
        :compared_selector_id => selector_ids[1],
        :property => (match_prop.to_f / unique_property_count.to_f),
        :value => (match_prop.to_f / unique_property_count.to_f),
      )

    end
    similarities
  end

end

app/controllers/project_files_controller.rb
class ProjectFilesController < TakiController
  before_action :set_project_file, only: [:show, :z_index, :similarity]

  # GET /
  def top
    @project_file = ProjectFile.new
  end

  def create
    @project_file = ProjectFile.create( file_params )
    redirect_to project_file_url(@project_file)
  end

  # GET /project_files
  # GET /project_files.json
  def index
    @project_files  = ProjectFile.limit(5).order(created_at: :desc)
  end

  # GET /project_files/:id
  # GET /project_files/:id.json
  def show
    selector_ids = @project_file.project_file_selectors.pluck(:id)
    @properties  = ProjectFileSelectorProperty.where(project_file_selector_id: selector_ids)
  end

  # GET /project_files/:id/z-index
  # GET /project_files/:id/z-index.json
  def z_index
    selector_ids = @project_file.project_file_selectors.pluck(:id)
    @properties = ProjectFileSelectorProperty.where({ name: 'z-index', project_file_selector_id: selector_ids}).order(value: :desc)
    @properties.sort! {|a, b| a.value.to_i <=> b.value.to_i }
  end

  # GET /project_files/:id/similarity
  # GET /project_files/:id/similarity.json
  def similarity
    # @simirarities = @project_file.calc_similarities
    # simirarities = ProjectFileSelector.includes(:project_file_selector_similarities).references(:property)
    similarities = ProjectFileSelector.where(project_file_id: @project_file.id).map(&:project_file_selector_similarities)
    render :json => similarities.page(1).par(10)
  end

  private
  def set_project_file
    @project_file = ProjectFile.find(params[:id])
    raise ActiveRecord::RecordNotFound if @project_file.blank?
  end

  def file_params
      params.require(:project_file).permit(:attachment)
  end

end

app/views/project_files/index.html.slim
- content_for :title do
  = @title

- content_for :description do
  = @description

.contents
  .inner
    table
      tbody
        tr
          th file_name
          th file_size
        - @project_files.each do |f|
          tr
            th= link_to f.attachment_file_name, project_file_path(f)
            td= f.attachment_file_size
    .prev
      =link_to "back to TOP", root_path

app/views/project_files/show.html.slim
- content_for :title do
  = @title

- content_for :description do
  = @description

.status
  .lead-text
    = "Finished analyze of CSS."
    br
    = "You can check summary for CSS."
.contents.bottom
  .inner
    h2 Check result
    dl.clearfix
      dt.link
        = link_to "z-index", z_index_project_file_path(@project_file)
      dd Check z-index property which is used in the CSS.
    dl.clearfix
      dt.link
        = link_to "similarity", similarity_project_file_path(@project_file)
      dd Check similarity property which is used in the CSS.
    h2 Summary of this CSS
    dl.clearfix
      dt Selectors Num
      dd
        = @properties.count
        span selectors

app/views/project_files/similarity.html.slim
- content_for :title do
  = @title

- content_for :description do
  = @description

.contents
  .inner
    table#table
      tbody
        tr
          th selector_id
          th selector_id
          th property similarity
          th value similarity
        /- @simirarities.each do |s|
        /  tr
        /    th= s[:combination][0]
        /    th= s[:combination][1]
        /    td= s[:property_similarity]
        /    td= s[:value_similarity]
    #pager
    .prev-btn
      =link_to "back to Summary", project_file_path(@project_file)

app/views/project_files/top.html.slim
- content_for :title do
  = @title

- content_for :description do
  = @description

.contents
  .inner
    .form-upload
      = form_for(@project_file) do |f|
        = f.text_field :status, class: "display-filename", readonly: true
        .input-file-box
          = f.file_field :attachment, class: "file bindChangeFile"
        .submit-box
          = f.submit class: "submit"

    h2 Check upload file.
    dl.clearfix
      dt.link
        = link_to "files", project_files_path
      dd Check your upload file.

app/views/project_files/z_index.html.slim
- content_for :title do
  = @title

- content_for :description do
  = @description

.contents
  .inner
    table
      tbody
        tr
          th selector
          th property
          th value
        - @properties.each do |p|
          tr
            th= p.project_file_selector.name
            td= p.name
            td= p.value
    .prev-btn
      =link_to "back to Summary", project_file_path(@project_file)